node setops.js "set1=a1.txt;set2=b1.txt;operation=intersection"
node setops.js "set1=a2.txt;set2=b2.txt;operation=difference"
node setops.js "set1=a3.txt;set2=b3.txt;operation=union"
node setops.js "set1=a4.txt;set2=b4.txt;operation=intersection"
node setops.js "set1=a.txt;set2=b4.txt;operation=intersection"